#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""voicebot - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Whisper (Speech-to-Text)
- Ollama (LLM)
- Piper (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""

import asyncio
import datetime
import json
import os
import re
import sys
from collections.abc import Sequence
from typing import NamedTuple
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

# .env BEFORE the domain import, not after. domain.py reads DOMAIN at import
# time, so the load_dotenv() further down ran too late: DOMAIN=insurance sat in
# .env while every call still ran car_spa. Only a shell `DOMAIN=... python bot.py`
# worked, which is exactly how it passed in testing and failed in use.
from dotenv import load_dotenv  # noqa: E402

# override=False: a shell variable must still win. With override=True this line
# stomped `DOMAIN=car_spa python bot.py`, so the documented way to run the other
# domain silently did nothing. The second load_dotenv below still uses
# override=True for the API keys, which is what that one is for.
load_dotenv(Path(__file__).parent / ".env", override=False)

from domain import (
    ACTIVE as ACTIVE_DOMAIN,
    CONTEXT_FILE,
    build_guard,
    build_system_prompt,
)
from guardrails import PriceGuard, is_machine_output
from redaction import redact

from openai import APIConnectionError, APIStatusError, APITimeoutError, RateLimitError
from loguru import logger
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.audio.vad.vad_analyzer import VADParams
from pipecat.frames.frames import (
    BotStoppedSpeakingFrame,
    LLMRunFrame,
    TranscriptionFrame,
    TTSTextFrame,
)
from pipecat.observers.base_observer import BaseObserver, FramePushed
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.worker import PipelineParams, PipelineWorker
from pipecat.processors.frame_processor import FrameDirection, FrameProcessor
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import (
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
)
from pipecat.evals.transport import EvalTransportParams
from pipecat.runner.types import RunnerArguments
from pipecat.services.llm_service import FunctionCallParams
from pipecat.services.stt_service import STTService
from pipecat.services.tts_service import TTSService
from pipecat.runner.utils import create_transport
from pipecat.services.assemblyai.stt import AssemblyAISTTService
from parkplus_stt import ParkPlusSTTService
from pipecat.services.elevenlabs.tts import ElevenLabsTTSService
from pipecat.services.groq.llm import GroqLLMService
from pipecat.services.groq.stt import GroqSTTService
from pipecat.services.ollama.llm import OLLamaLLMService
from pipecat.services.piper.tts import PiperTTSService
from pipecat.services.sarvam.tts import SarvamTTSService
from pipecat.transcriptions.language import Language
from pipecat.services.whisper.stt import WhisperSTTService
from pipecat.transports.base_transport import BaseTransport, TransportParams
from pipecat.utils.text.base_text_filter import BaseTextFilter
from pipecat.utils.text.markdown_text_filter import MarkdownTextFilter
from pipecat.workers.runner import WorkerRunner

load_dotenv(override=True)  # cwd .env too, for a run from another directory

BOOKING_LOG = Path(__file__).parent / "booking_requests.jsonl"
CALL_LOG = Path(__file__).parent / "call.log"


_LOGGING_READY = False


def _setup_logging() -> None:
    """One readable feed of the call, instead of Pipecat's full DEBUG firehose.

    At DEBUG, Pipecat prints the entire 2000-token system prompt on every connect
    and the entire message context on every turn. A five minute call was 5000+
    lines, and the three lines that mattered — what the caller said, what Monika
    said, what broke — were buried in ICE candidates. INFO drops all of that;
    CallLogObserver puts the conversation back in, one line per turn.

    LOG_LEVEL=DEBUG brings the firehose back when a frame-level bug needs it.
    The same feed is written to call.log so a whole call can be attached as a
    file rather than pasted.

    Called from run_bot, not from __main__, because pipecat.runner.run.main()
    does its own logger.remove() and re-adds stderr at DEBUG — configuring
    before it just gets wiped. Guarded because run_bot runs once per call and
    a second logger.add(CALL_LOG) would write every line to the file twice.
    """
    global _LOGGING_READY
    if _LOGGING_READY:
        return
    _LOGGING_READY = True
    level = os.getenv("LOG_LEVEL") or "INFO"
    logger.remove()
    fmt = "{time:HH:mm:ss} | {level: <7} | {message}"
    logger.add(sys.stderr, level=level, format=fmt)
    logger.add(CALL_LOG, level=level, format=fmt, rotation="5 MB", retention=3)


# Silence is not silent on a phone line, and ASR models answer it with whatever
# they heard most in training. MEASURED from call.log: on Hindi calls where the
# caller said nothing, AssemblyAI produced "Thank you.", "Thank", "Cool." and
# "So yeah." — English, in a Devanagari conversation. The bot then answered them,
# which is why a caller said "ये बाहर की वो नोइज़ ले लेता है".
#
# Only phrases with BOTH properties are listed: they are documented ASR
# silence-hallucinations, and a Gurugram caller booking a car wash would not say
# them alone as a turn. "Hello", "bolo", "okay", "yes" and "bye" are NOT here on
# purpose — "Bolo." appears in the same log and is a real caller saying बोलो in
# Latin script. Dropping short Latin text as a class would eat real speech.
#
# That last point got sharper with PARKPLUS_STT_URL: Park+'s ASR returns
# ROMANISED Hindi, so "Haan ji meri creta hai" is Latin-only too. The Devanagari
# check below is now an early exit for AssemblyAI's output, not the main defence
# — this exact phrase list is. Keep it exact-match and keep it short.
_NOISE_TRANSCRIPTS = frozenset({
    "thank", "thank you", "thanks", "thanks for watching", "thank you very much",
    "cool", "so yeah", "you", "uh", "um", "hmm", "mm", "mhm", "ah",
})


class NoiseGate(FrameProcessor):
    """Drops transcripts that are the transcriber talking to itself.

    Sits between the STT and the user aggregator, so a dropped line never reaches
    the context and never earns a reply. The VAD above is the real fix and this is
    the net under it: VAD decides whether audio is speech, this decides whether a
    finished transcript is a turn.
    """

    def __init__(self):
        super().__init__()
        self.dropped: list[str] = []

    @staticmethod
    def _is_noise(text: str) -> bool:
        stripped = text.strip()
        if not stripped:
            return True
        # Anything in Devanagari is the caller. Only Latin-only text can be one of
        # the hallucinations above, which keeps real Hindi safe whatever it says.
        if re.search(r"[\u0900-\u097F]", stripped):
            return False
        return re.sub(r"[^\w\s]", "", stripped).strip().lower() in _NOISE_TRANSCRIPTS

    async def process_frame(self, frame, direction: FrameDirection):
        await super().process_frame(frame, direction)
        if isinstance(frame, TranscriptionFrame) and self._is_noise(frame.text):
            self.dropped.append(frame.text.strip())
            logger.info(f"NOISE  | dropped {frame.text.strip()!r}")
            return
        await self.push_frame(frame, direction)


class CallLogObserver(BaseObserver):
    """Logs the call as a conversation: one CALLER line, one MONIKA line.

    Pipecat's own transcription observer logs at DEBUG, which is exactly the
    level being suppressed, and it only covers the caller's side. This watches
    both: the STT's final transcripts, and the sentences actually handed to the
    TTS — i.e. what the caller really heard, after the guardrails rewrote it.
    """

    def __init__(self, guard: PriceGuard | None = None):
        super().__init__()
        self._said: list[str] = []
        # The same PriceGuard the TTS filter uses. The filter only ever sees what
        # the BOT says, so on its own it cannot know whether the caller ever named
        # a car — and "₹499 (Hyundai Creta के लिए)" for a caller who never said
        # Creta passes every content check. This is the only place both sides of
        # the conversation are visible, so this is where that gets recorded.
        self._guard = guard

    async def on_push_frame(self, data: FramePushed):
        frame = data.frame
        if isinstance(frame, TranscriptionFrame) and isinstance(data.source, STTService):
            if frame.text.strip():
                # redact(), not the raw transcript. On a KYC call the customer
                # reads their PAN and Aadhaar out loud, and call.log is an
                # unrestricted file — the insurance pack forbids raw identity
                # numbers landing in one. The bot still SEES the real value; only
                # the log is masked.
                logger.info(f"CALLER | {redact(frame.text.strip())}")
                # Just hand it to the guard. This used to read
                # `self._guard.car_known` first — a car-spa-only attribute — and
                # crashed every insurance call with
                # "'KycGuard' object has no attribute 'car_known'". The observer
                # has no business knowing what a domain gates on; note_caller
                # returns True only on the turn something unlocks.
                if self._guard and self._guard.note_caller(frame.text):
                    logger.info("GUARD unlocked by the caller's answer")
        elif isinstance(frame, TTSTextFrame) and isinstance(data.source, TTSService):
            # The source check is not decoration. on_push_frame fires once per
            # PROCESSOR HOP, so one sentence travelling TTS -> transport.output
            # arrived here twice and every MONIKA line in the 21:55 log was
            # printed doubled ("दो मिनट बात कर लें? दो मिनट बात कर लें?"). The
            # caller heard it once; only the log was wrong.
            self._said.append(frame.text)
        elif isinstance(frame, BotStoppedSpeakingFrame) and self._said:
            # Joined on flush: the LLM streams a turn as several sentences, and
            # one log line per turn is what makes the transcript readable.
            logger.info(f"MONIKA | {redact(' '.join(self._said).strip())}")
            self._said.clear()

# Anything the TTS could actually pronounce. Sarvam rejects a chunk with none of
# it ("400: Text must contain at least one character from the allowed languages"),
# which is what a stray "." from the sentence splitter produces.
_SPEAKABLE_RE = re.compile(r"[^\W_]", re.UNICODE)


def _message_role(message) -> str | None:
    """Role of a context message, whether it is a dict or an LLMSpecificMessage."""
    inner = getattr(message, "message", message)
    return inner.get("role") if isinstance(inner, dict) else None


def _message_text(message) -> str:
    """Text of a context message, whether it is a dict or an LLMSpecificMessage."""
    inner = getattr(message, "message", message)
    content = inner.get("content") if isinstance(inner, dict) else None
    return content if isinstance(content, str) else ""


def _estimate_tokens(text: str) -> int:
    """Rough token cost of a message, for the history budget.

    3.2 chars/token is the ratio measured against Groq's own prompt_tokens on this
    Devanagari/English mix (scratchpad/t_tokens.py). The 4 is the per-message
    role/scaffolding overhead, which matters when the history is many short turns.
    An estimate is fine here — it decides what to drop, never what to bill.
    """
    return int(len(text) / 3.2) + 4


def _reasoning_effort(model: str) -> str:
    """The lowest reasoning setting each model family will actually accept.

    Both families reason before answering and both need that turned down for a
    phone call, but they disagree on the word for it: Groq's gpt-oss rejects
    "none" outright — `400: reasoning_effort must be one of low, medium, or
    high` — and its minimum is "low". Hard-coding qwen's "none" meant that
    switching GROQ_MODEL to gpt-oss made every single turn fail with a 400, so
    the value has to follow the model rather than sit next to it.
    """
    return "low" if model.startswith("openai/gpt-oss") else "none"


def _stt_keyterms() -> list[str]:
    """Domain vocabulary to bias the transcriber toward.

    The proper nouns are where a Hinglish call actually breaks. In one real car
    spa call "car spa" came back as "कारिस पर" and "Royal Enfield" as "रॉयल
    फील्ड" — the bot then reasoned correctly about the wrong words. For a KYC
    call it is the insurer names and the field labels the customer reads off
    their own screen.

    The list lives in the DOMAIN's context.json, not here. It used to be built
    from car-spa price tiers inline, which meant this function raised
    KeyError: 'pricing' under DOMAIN=insurance — masked only because the Park+
    STT branch was selected and never called it. Switching STT would have killed
    the bot at startup.
    """
    ctx = json.loads(CONTEXT_FILE.read_text())
    return sorted(ctx.get("stt_keyterms", []))


def _extra_groq_keys() -> list[str]:
    """Every Groq key in the environment besides GROQ_API_KEY, for the failover.

    Quotas are per key (measured, scratchpad/t_keys.py), so this is the one free
    lever on the free tier that costs no prompt quality: each extra key is another
    8000 tokens/minute, and ~3k/turn means roughly 2.6 more turns a minute.
    Anything named GROQ_API_KEY_2, _3, ... is picked up with no code change.
    """
    return [
        v
        for k, v in sorted(os.environ.items())
        if v and k.startswith("GROQ_") and "API_KEY" in k and k != "GROQ_API_KEY"
    ]


# Fallback order for a rate-limited turn, best Hindi first. Each (key, model)
# pair is its own 8000 tokens/minute — measured 2026-09-14, scratchpad/t_models.py:
# burning qwen3.8 down by 5226 on one key left qwen3.6, gpt-oss-20b and
# gpt-oss-120b on that SAME key untouched to the token. So the budget is not two
# buckets, it is keys x models: with two keys, eight.
#
# qwen3.8 is the benchmarked best on Hindi and stays first. The rest are ordered
# by how close they are to it, and they only ever serve a turn qwen3.8 could not:
# a slightly stiffer sentence beats the dead air the caller got on 2026-09-14,
# and the guardrails are deterministic, so a weaker model still cannot invent a
# price, a slot or a confirmed booking.
# Every name here is verified against GET /v1/models on the live account
# (2026-09-15). "qwen/qwen3.6-27b" used to sit second in this list and DOES NOT
# EXIST — Groq 404s it with model_not_found, which is not a rate limit, so the
# rotation raised out and the 21:55 call died on turn five. Do not add a model
# here from memory or from a docs page; list the account's models first.
FALLBACK_MODELS = [
    "qwen/qwen3.8-27b",
    "openai/gpt-oss-120b",
    "openai/gpt-oss-20b",
]

# Gemini speaks OpenAI on this path, so it joins the rotation as a base_url swap
# rather than a second service — the pipeline, the TTS and PriceGuardFilter are
# untouched. (Gemini Live, the speech-to-speech service, is deliberately NOT used:
# it pushes TTSAudioRawFrame straight out of the LLM, so there is no text
# checkpoint where the price guard could run before the caller hears the number.)
# Park+'s own vLLM server. No quota, no per-minute bucket, no daily cap — which is
# why it goes FIRST in the rotation and everything else becomes failover.
# MEASURED 2026-09-18 against the live endpoint:
#   - TTFT median 0.70s streaming (min 0.56, max 1.15). That is the number that
#     matters for voice: TTS starts on the first sentence, not on the last token.
#     Full completion is ~5.3s, which the caller never waits for.
#   - 65536 context, one model, served by vLLM.
#   - TLS validates. The curl that came with it used -k; that is not needed, and
#     disabling verification on a call carrying customer phone numbers is worse
#     than the inconvenience it saves. Verification stays ON here.
#   - With NOTHING set it writes its reasoning straight into content, in English,
#     with no <think> tags and no reasoning_content field to strip: "The user is
#     asking about Creta car spa price in Hindi. Let me think about this." On a
#     call that is spoken aloud. Both switches below turn it off; both are sent.
# Set PARKPLUS_LLM_URL to put it in the rotation; unset, nothing changes.
PARKPLUS_BASE_URL = os.getenv("PARKPLUS_LLM_URL")
PARKPLUS_MODEL = os.getenv("PARKPLUS_LLM_MODEL") or "ulkaa/Ornith-1.5-35B-A3B-AWQ-INT4"

# Park+'s Bifrost gateway, which fronts Gemini with Park+'s own billing — so no
# 20-requests-a-day free-tier cap. Auth is a VIRTUAL KEY in an x-bf-vk header,
# not a bearer token: without it the gateway answers
# "virtual key is required. Provide a virtual key via the x-bf-vk header".
# Model ids are namespaced, e.g. "gemini/gemini-3.6-flash".
#
# The header is set on the shared client for the whole rotation. Groq and the
# Park+ vLLM ignore an unknown header, so one client serves every endpoint and
# the failover stays a base_url swap.
BIFROST_BASE_URL = os.getenv("BIFROST_URL") or "https://bifrost.parkplus.io/v1"
BIFROST_VK = os.getenv("BIFROST_VK")
BIFROST_MODELS = [
    m.strip() for m in (os.getenv("BIFROST_MODELS") or "gemini/gemini-3.6-flash").split(",")
    if m.strip()
]

GEMINI_BASE_URL = "https://generativelanguage.googleapis.com/v1beta/openai"

# MEASURED 2026-09-15 on a real key, scratchpad/t_gemini*.py:
#   - Quality is there: gemini-3.5-flash scored FAIL 0/5 GUARDED 0/5 on the Hindi
#     bench, the same clean sheet as qwen3.8.
#   - But the free tier is TINY, and the number that matters is the daily one:
#       GenerateRequestsPerDayPerProjectPerModel-FreeTier = 20
#     Twenty requests per DAY per model. Two models is 40, and a Car Spa call
#     spends 6-10 turns, so this whole provider is 2-4 calls a day. (The per
#     minute cap, GenerateRequestsPerMinutePerProjectPerModel-FreeTier = 5, is
#     the one you notice first and the one that does not matter.) Groq gives
#     1000 requests/day per key per model — 8000/day on two keys. 200x more.
#   - Per project, so extra Google keys in the same project buy nothing. Billing
#     on the project, or a second project, is what would make this a real bucket.
#   - gemini-2.5-* is 404 "no longer available to new users"; 3.8/3.7/3.1-lite
#     returned 503 "high demand" on a one-token call; 3.5-flash-lite 400s on any
#     request carrying reasoning_effort. Hence exactly these two.
# So it is last in the rotation and it is emergency reserve, not capacity: it
# answers a handful of turns Groq could not, on a different provider's
# infrastructure, and then it is spent for the day. Latency also measured
# 3.2-16.2s per turn with one 60s timeout, against Groq's sub-second.
GEMINI_MODELS = ["gemini-3.5-flash", "gemini-3.6-flash"]

# Groq says "Please try again in 617.142857ms"; Gemini says "Please retry in
# 54.441716995s". Same fact, two spellings, so match both.
_RETRY_AFTER_RE = re.compile(r"(?:try again|retry) in ([\d.]+)(ms|s)")


def _retry_after_seconds(error: Exception) -> float | None:
    """How long the provider said to wait, from the 429 body. None if it didn't say."""
    m = _RETRY_AFTER_RE.search(str(error))
    if not m:
        return None
    value = float(m.group(1))
    return value / 1000 if m.group(2) == "ms" else value


def _is_retryable(error: Exception) -> bool:
    """Would another endpoint plausibly answer this?

    Rate limits and outages, yes — that is the whole point of the rotation, and
    Gemini's "503 This model is currently experiencing high demand" is an outage
    that arrives looking nothing like a 429. A 400 or a 401 is our own request
    being wrong, and re-sending it to four more endpoints just spends four more
    seconds before failing anyway, so those still raise immediately.
    """
    if isinstance(error, (RateLimitError, APITimeoutError, APIConnectionError)):
        return True
    return isinstance(error, APIStatusError) and error.status_code >= 500


_NO_TOOL_SUPPORT_RE = re.compile(
    r"enable-auto-tool-choice|tool-call-parser|does not support tools", re.IGNORECASE)


def _is_dead_endpoint(error: Exception) -> bool:
    """Is this endpoint permanently unusable, rather than busy?

    A model that does not exist, a key that is not authorised: retrying it on the
    next turn is guaranteed to fail the same way. This is not hypothetical — the
    21:55 call died because "qwen/qwen3.6-27b" was in FALLBACK_MODELS and Groq
    404s it. Worse, the rotation had already pointed `self._settings.model` at it,
    so it stayed selected and every LATER turn 404'd too: one wrong string in a
    list took out the whole call rather than one turn.
    """
    if isinstance(error, APIStatusError) and error.status_code in (401, 403, 404):
        return True
    # vLLM answers every tools request with 400 when the server was launched
    # without them: `"auto" tool choice requires --enable-auto-tool-choice and
    # --tool-call-parser to be set`. Every turn carries tools, so that endpoint
    # can never serve this bot — but it is a 400, and a bare 400 rule would also
    # retire an endpoint over one malformed request. Match the message, retire the
    # endpoint, and let the call continue on the next one instead of dying.
    return _NO_TOOL_SUPPORT_RE.search(str(error)) is not None


class Endpoint(NamedTuple):
    """One (provider, key, model) the rotation can fall back to."""

    api_key: str
    model: str
    base_url: str | None  # None = this service's own default, i.e. Groq
    provider: str


class FailoverLLMService(GroqLLMService):
    """LLM that survives a rate limit by moving to another key, model OR provider.

    Groq's free tier grants 8000 tokens/minute and this call spends ~3k of them
    every turn, so one bucket buys 2.3 turns a minute. A real Car Spa call — the
    caller asking why not their regular cleaner, what is included, how often,
    then giving five fields — runs 6 to 10. On 2026-09-14 the bot rotated its two
    keys and hit 429 on both on every single turn from 20:56 on; the caller heard
    nothing and the call was over before a booking could exist.

    Rotating (key, model) instead of key alone turns two budgets into eight. Gemini
    adds two more, and it is worth being honest about how small they are: 20
    requests per day per model on the free tier, so a few calls' worth in total.
    What it buys is not capacity, it is independence — Groq meters tokens per
    minute, Gemini meters requests per day, and a Groq outage is not a Gemini
    outage. It answers the turn where every Groq bucket is spent, which on
    2026-09-14 was the turn where the caller heard nothing at all.

    When every endpoint is spent, the provider's own 429 says how long to wait, and
    a wait under `max_wait` is taken rather than failing: a caller forgives one
    beat of silence, not a line that never comes.
    """

    def __init__(
        self,
        *,
        api_key: str,
        backup_api_keys: Sequence[str] = (),
        fallback_models: Sequence[str] = (),
        gemini_api_key: str | None = None,
        gemini_models: Sequence[str] = (),
        parkplus_url: str | None = None,
        parkplus_model: str = "",
        parkplus_api_key: str | None = None,
        bifrost_url: str | None = None,
        bifrost_models: Sequence[str] = (),
        max_history_tokens: int = 400,
        max_wait: float = 2.5,
        request_timeout: float = 10.0,
        **kwargs,
    ):
        super().__init__(api_key=api_key, **kwargs)
        # dict.fromkeys: a duplicated key is a duplicate BUDGET in the rotation but
        # not in reality, so it would just spend a turn re-hitting a spent quota.
        keys = list(dict.fromkeys(k for k in (api_key, *backup_api_keys) if k))
        primary = self._settings.model
        models = list(dict.fromkeys([primary, *fallback_models]))
        # Model-major: every key on the best model before any key on the second.
        # A weaker model is a real quality cost, so it is only reached once the
        # good one is spent everywhere.
        self._endpoints = [Endpoint(k, m, None, "groq") for m in models for k in keys]
        # Park+'s own server has no quota at all, so it leads and everything
        # below it becomes failover rather than capacity.
        if parkplus_url:
            self._endpoints.insert(
                0, Endpoint(parkplus_api_key or "not-needed", parkplus_model,
                            parkplus_url, "parkplus"))
        # Bifrost leads, and the reason is NOT time to first token — Park+ wins
        # that, 0.95s to 1.92s. It is reply LENGTH, which is what the caller
        # actually waits through. MEASURED 2026-09-18 on the same prompt:
        #     gemini/gemini-3.6-flash  131 chars -> ~10.7s of speech, full 2.46s
        #     ulkaa/Ornith             225 chars -> ~18.4s of speech, full 7.18s
        # At ~12 characters of Hindi per second that is nearly eight seconds per
        # turn, against a one-second penalty on the first token. Park+ stays
        # right behind it as the no-quota fallback.
        if bifrost_url:
            for model in reversed(list(bifrost_models)):
                self._endpoints.insert(0, Endpoint("not-needed", model, bifrost_url, "bifrost"))
        # Gemini last: it benchmarks as well as qwen3.8 on Hindi but answers in
        # 3-16s against Groq's sub-second, so it is what stands between the caller
        # and dead air, not what serves a normal turn.

        if gemini_api_key:
            self._endpoints += [
                Endpoint(gemini_api_key, m, GEMINI_BASE_URL, "gemini") for m in gemini_models
            ]
        self._index = 0
        # Whatever GroqLLMService pointed the client at, so rotating back off a
        # Gemini endpoint restores it instead of guessing the URL.
        self._default_base_url = self._client.base_url
        self._max_history_tokens = max_history_tokens
        self._max_wait = max_wait
        # The OpenAI SDK defaults to max_retries=2 and honours Groq's Retry-After
        # header, so it swallowed every 429 and slept through it instead: the
        # failover below never fired, and callers waited 13-29s in silence for a
        # reply. Surfacing the 429 immediately is what makes the second key useful.
        self._client.max_retries = 0
        # ...and it defaults to a 600s timeout, which on a phone call is not a
        # timeout at all. One measured Gemini request took over 60s. Past ~10s the
        # caller has already said "hello?" or hung up, so cut it off and let the
        # next endpoint answer.
        self._client.timeout = request_timeout
        # Point the client at endpoint 0. Without this the LIST says Park+ leads
        # while the CLIENT still holds whatever super().__init__ configured, so
        # the preferred endpoint is only ever reached after a failure wraps the
        # rotation around to it — i.e. never, on a healthy call.
        self._apply_endpoint(announce=False)

    def _trim_history(self, context) -> None:
        """Keep the newest turns that fit a TOKEN budget, not a message count.

        The system prompt plus tool schemas is ~2.5k tokens and the whole context
        is resent every turn, so on Groq's 7000 ITPM free tier an unbounded
        history is a death spiral: a five minute call had grown to 4669 prompt
        tokens/turn, which rate limited every remaining turn.

        Counting MESSAGES did not stop it. On the 2026-09-14 20:30 call the cap of
        16 was never reached and the prompt still climbed 2556 -> 3586 tokens,
        because a caller thinking out loud on an open mic produces single turns of
        400+ characters ("कॉन्टेक्स्ट में थोड़ी सी वो है, but हाँ वैसे सही डेट ही
        है..." ran 700). Sixteen of those is not 500 tokens, it is 1100, and the
        429s landed exactly on the turns that followed them. A budget is what the
        rate limit actually meters, so budget it directly.
        """
        messages = context.get_messages()
        # An assistant turn that was never speech does not belong in the history
        # either. On a live call qwen answered with a JSON error blob; the TTS
        # filter stops the caller HEARING it, but it stayed in the context as a
        # model turn and the six turns after it degraded ("आप रात को कब आना चाहते
        # हैं?" on a doorstep service). The filter sits downstream of the context
        # and cannot reach this, so it is dropped here, where the history lives.
        poisoned = [
            m
            for m in messages
            if _message_role(m) == "assistant"
            and is_machine_output(_message_text(m))
        ]
        if poisoned:
            logger.error(f"CONTEXT dropping {len(poisoned)} non-speech assistant turn(s)")
            messages = [m for m in messages if m not in poisoned]
            context.set_messages(messages)

        # Newest first until the budget runs out. The last two are kept whatever
        # they cost — the caller's current turn and what it answers are the one
        # thing the model cannot do without.
        kept: list = []
        spent = 0
        for message in reversed(messages):
            cost = _estimate_tokens(_message_text(message))
            if len(kept) >= 2 and spent + cost > self._max_history_tokens:
                break
            kept.append(message)
            spent += cost
        kept.reverse()

        # A tool result whose assistant tool_call was trimmed away is an orphan
        # and Groq rejects the request outright, so drop any leading one.
        while kept and _message_role(kept[0]) == "tool":
            kept.pop(0)
        if len(kept) < len(messages):
            logger.debug(f"CONTEXT {len(messages)} -> {len(kept)} msgs, ~{spent} tokens")
            context.set_messages(kept)

    async def get_chat_completions(self, context):
        self._trim_history(context)
        # Every (key, model) bucket once, then — only if they are all spent —
        # wait out the shortest of them. Sleeping first would add a beat of
        # silence to turns that another bucket could have answered instantly.
        shortest_wait: float | None = None
        for attempt in range(len(self._endpoints)):
            try:
                return await super().get_chat_completions(context)
            except Exception as e:
                # A dead endpoint leaves the rotation entirely, so it cannot be
                # selected again for the rest of the call.
                if _is_dead_endpoint(e):
                    self._retire_endpoint(e)
                    if not self._endpoints:
                        raise
                    continue
                if not _is_retryable(e):
                    raise
                wait = _retry_after_seconds(e)
                if wait is not None:
                    shortest_wait = wait if shortest_wait is None else min(shortest_wait, wait)
                if attempt < len(self._endpoints) - 1:
                    self._next_endpoint(e)
                    continue

                if shortest_wait is not None and shortest_wait <= self._max_wait:
                    logger.warning(
                        f"All {len(self._endpoints)} LLM buckets spent — "
                        f"waiting {shortest_wait:.1f}s rather than going silent"
                    )
                    await asyncio.sleep(shortest_wait)
                    self._next_endpoint(e)
                    return await super().get_chat_completions(context)
                raise

    def _retire_endpoint(self, error: Exception) -> None:
        """Drop the current endpoint for good and point the client at the next."""
        dead = self._endpoints.pop(self._index)
        logger.error(
            f"DROPPED {dead.provider}:{dead.model} from the rotation for this call "
            f"— {type(error).__name__}: {str(error)[:120]}"
        )
        if not self._endpoints:
            return
        self._index %= len(self._endpoints)
        self._apply_endpoint(error)

    def _next_endpoint(self, error: Exception | None = None) -> None:
        self._index = (self._index + 1) % len(self._endpoints)
        self._apply_endpoint(error)

    def _apply_endpoint(self, error: Exception | None = None, announce: bool = True) -> None:
        endpoint = self._endpoints[self._index]
        self._client.api_key = endpoint.api_key
        # base_url is what makes a Gemini endpoint reachable from a Groq service.
        # httpx wants a trailing slash or it drops the last path segment, which
        # turns /v1beta/openai/chat/completions into /v1beta/chat/completions.
        self._client.base_url = (
            f"{endpoint.base_url}/" if endpoint.base_url else self._default_base_url
        )
        self._settings.model = endpoint.model
        extra = {**self._settings.extra,
                 "reasoning_effort": _reasoning_effort(endpoint.model)}
        if endpoint.provider == "parkplus":
            # Belt and braces. reasoning_effort alone silenced the thinking in
            # testing, but the failure it prevents is the bot reading its own
            # English reasoning to a Hindi caller, so send the vLLM switch too.
            #
            # It MUST go inside extra_body. base_llm does params.update(extra)
            # and then create(**params), and the OpenAI SDK rejects any kwarg it
            # does not define: passing it at the top level raised
            # "AsyncCompletions.create() got an unexpected keyword argument
            # 'chat_template_kwargs'" on every single turn of the 16:31 call, and
            # a local TypeError is not an APIStatusError, so the failover could
            # not see it and the bot said nothing at all.
            extra["extra_body"] = {"chat_template_kwargs": {"enable_thinking": False}}
        else:
            extra.pop("extra_body", None)
        self._settings.extra = extra
        if not announce:
            return
        why = type(error).__name__ if error else "rotating"
        logger.warning(
            f"{why} — trying {endpoint.provider}:{endpoint.model} "
            f"on key #{self._keys.index(endpoint.api_key) + 1}"
        )

    @property
    def _keys(self) -> list[str]:
        """Distinct keys, in rotation order — for logging which one is in play."""
        return list(dict.fromkeys(e.api_key for e in self._endpoints))


class PriceGuardFilter(BaseTextFilter):
    """Runs the deterministic price check on every sentence before it is spoken.

    Sits in the TTS service's text_filters, so it catches the text on its way to
    the voice regardless of which model produced it or what the prompt said.
    """

    # Every list PriceGuard appends to, and what to say when it grows. Was six
    # positional entries in a tuple indexed by hand; each new guard meant a new
    # magic index, so it is a table now — adding a guard is one row.
    # WARNING is for counters that only observe (nothing was changed); ERROR is
    # for text that was actually rewritten or dropped before the caller heard it.
    # Kept only as the car spa's table; a guard that declares its own COUNTERS
    # (see domains/insurance/guard.py) overrides it, because which rules exist
    # is a property of the domain, not of this filter.
    _COUNTERS = (
        ("blocked", logger.error, "blocked invented price(s)"),
        ("odd_times", logger.warning, "saw a non-standard slot time"),
        ("false_confirmations", logger.error, "rewrote a booking claimed as done"),
        ("romanised", logger.warning, "SCRIPT DRIFT, romanised (not rewritten)"),
        ("labels", logger.error, "stripped a leaked speaker label"),
        ("availability_claims", logger.error, "rewrote a slot/area availability claim"),
        ("damage_promises", logger.error, "rewrote a damage/liability promise"),
        ("body_type_asks", logger.error, "rewrote a hatchback/sedan/SUV question"),
        ("machine_output", logger.error, "DROPPED non-speech output"),
        ("priced_before_car", logger.error, "blocked a price before the caller named a car"),
        ("self_narration", logger.error, "DROPPED the model thinking out loud"),
    )

    def __init__(self, guard=None):
        self._guard = guard or PriceGuard()
        counters = getattr(self._guard, "COUNTERS", None)
        if counters:
            levels = {"error": logger.error, "warning": logger.warning,
                      "info": logger.info}
            self._counters = tuple((n, levels[lvl], what) for n, lvl, what in counters)
        else:
            self._counters = self._COUNTERS

    async def filter(self, text: str) -> str:
        # The sentence splitter can emit a chunk that is pure punctuation (a lone
        # "." after "gunga.."), which Sarvam 400s on and then drops the WebSocket,
        # costing a reconnect mid-call. TTS skips a filter that returns empty.
        if not _SPEAKABLE_RE.search(text):
            return ""

        g = self._guard
        before = {name: len(getattr(g, name)) for name, _, _ in self._counters}
        cleaned = g.check(text)
        for name, log, what in self._counters:
            seen = getattr(g, name)
            if len(seen) > before[name]:
                log(f"GUARDRAIL {what} {seen[before[name]:]} in: {text!r}")
        return cleaned

    async def handle_interruption(self):
        pass

    async def reset_interruption(self):
        pass


async def record_booking_request(
    params: FunctionCallParams,
    service: str,
    car: str,
    area: str,
    slot_preference: str,
    phone: str,
):
    """Note the booking request for the team to confirm. Call once you have all
    five. Records only — it does NOT book or confirm.

    Args:
        service: Full Car Spa Premium, Full Car Spa Basic or Exterior Only.
        car: Brand and model, e.g. "Hyundai Creta".
        area: Area or pincode in Gurugram.
        slot_preference: Day and time, in the customer's own words.
        phone: Callback number as given.
    """
    # The docstring above IS the tool schema and is re-sent on every turn, so it
    # carries only what the parameter names do not already say. Notes like this
    # one belong here, in a comment, where the model is never charged for them.
    request = {
        "ts": datetime.datetime.now().isoformat(),
        "service": service,
        "car": car,
        "area": area,
        "slot_preference": slot_preference,
        "phone": phone,
    }
    with BOOKING_LOG.open("a") as f:
        f.write(json.dumps(request, ensure_ascii=False) + "\n")
    logger.info(f"Booking request recorded: {request}")
    # The only status this tool can ever return. There is deliberately no
    # confirm_booking tool and no fee-waiver tool, so "your booking is confirmed"
    # and "I've waived the fee" are not things the model is able to transact —
    # the guardrail is the tool surface, not just the prompt.
    await params.result_callback(
        {
            "status": "pending_confirmation",
            "say": "Request noted. Tell the customer the team will confirm shortly. "
            "Do NOT say it is confirmed or that the slot is available.",
        }
    )


# How many times a caller has to ask before the call is really handed over.
# The counter lives here, not in the prompt, because the model cannot count its
# own turns: on a live call it called the handover tool on the caller's FIRST
# "owner का number दो" and then spent four turns promising a colleague who was
# never coming. The model still calls the tool whenever it thinks handover — the
# tool decides whether that is what actually happens.
ESCALATE_AFTER_ASKS = 3

# What to do instead, per ask. Indexed by ask number; the last entry is reached
# only if ESCALATE_AFTER_ASKS is raised past the list.
_DEFLECTIONS = [
    "Do NOT hand over. Apologise once in half a sentence, then solve it yourself: "
    "answer what they actually need — price, what is included, a slot, the booking, "
    "a policy — in one or two sentences, and ask the one question that moves it on.",
    "Still do NOT hand over. Say plainly what you CAN do right now — note the "
    "booking request, note a callback, take the area and the slot — and offer that. "
    "You have no colleague's phone number to give out, so never promise one.",
]


def _make_escalate_tool():
    """Build a per-session handover tool. The closure is the call's ask counter."""
    asks = 0

    async def escalate_to_human(params: FunctionCallParams, reason: str):
        """Ask to hand the call to a human agent. Call this EVERY time the customer
        asks for a person, a manager or an owner's number, is angry, wants to
        cancel or refund, or you failed to understand twice. Follow its reply
        exactly — it does NOT always hand over.

        Args:
            reason: Short note on why, for the human picking it up.
        """
        nonlocal asks
        asks += 1
        if asks < ESCALATE_AFTER_ASKS:
            logger.info(
                f"Escalation ask {asks}/{ESCALATE_AFTER_ASKS} held back: {reason}"
            )
            await params.result_callback(
                {
                    "status": "handle_it_yourself",
                    "asks_so_far": asks,
                    "say": _DEFLECTIONS[min(asks, len(_DEFLECTIONS)) - 1],
                }
            )
            return
        logger.warning(f"ESCALATION (ask {asks}): {reason}")
        await params.result_callback(
            {
                "status": "escalating",
                "say": "Tell the customer you are putting them through to a colleague. "
                "One short line, then stop — do not start a new question.",
            }
        )

    return escalate_to_human

# There used to be a block of "VOICE OUTPUT RULES" appended here for every voice.
# Measured against Groq's own token count it cost ~150 tokens on EVERY turn, and
# all of it except the Roman-script rule below was either already in the system
# prompt (no markdown, garbled transcripts, slot times read back verbatim) or
# actively wrong: it said "say numbers and currency in words", while the prompt
# says digits + रुपये because that is what Sarvam pronounces correctly. The two
# instructions contradicted each other on every single turn.
# Reply LENGTH is this bot's latency, not the LLM. MEASURED 2026-09-18 against
# Sarvam at pace 1.15 — roughly 12 characters of Hindi per second of speech:
#     21 chars  -> speaks for  1.2s
#    131 chars  -> speaks for  9.1s   (the greeting)
#    167 chars  -> speaks for 13.7s   (+4.5s to synthesise)
# while the LLM's time to first token is 0.93s. On the 18:50 call the caller gave
# up and repeated themselves before the bot finished its first reply.
#
# TWO attempts to fix this from the prompt were tried and BOTH were reverted,
# because the eval caught each one trading correctness for speed:
#   "ONE sentence, then stop"      -> price_needs_car 1/4. Judge: "the bot is
#                                     looping and has not provided an actual
#                                     price answer."
#   "under 25 words, answer first" -> price_needs_car 3/4. Judge: "bot is still
#                                     asking clarifying questions and has not
#                                     given a final answer."
# Squeezing the word budget makes the model drop the ANSWER and keep the
# question. Empty is the state that passes 4/4, so empty it stays.
#
# The real levers, in order of size, none of them free:
#   1. SARVAM_PACE above 1.15 — deterministic, but past ~1.3 Hindi consonants
#      smear, so it needs a human to listen before it ships.
#   2. A shorter system prompt, so the model has fewer things it feels obliged
#      to say in one turn. This is prompt work with the eval as the check.
#   3. A faster TTS. Sarvam took 4.5s to synthesise 167 chars, which is latency
#      before a single word is spoken.
# Do NOT reach for a different LLM: gemini-3.5-flash measured 8.17s to first
# token against Park+'s 0.93s on this same prompt.
VOICE_MODE_ADDENDUM_COMMON = ""

# The local Piper voice (en_US-lessac-medium) only knows English phonemes, so
# Devanagari comes out as garbled noise on that path — force Roman script there.
# Sarvam and ElevenLabs' multilingual model speak Hindi properly and need none
# of this.
VOICE_MODE_ADDENDUM_ROMAN_ONLY = """

- Never use Devanagari script. If you mix in Hindi words, spell them in Roman
  script (e.g. "kitna time lagega", not "कितना समय लगेगा") — the voice reading
  your words only knows English phonetics.
"""


async def run_bot(transport: BaseTransport, runner_args: RunnerArguments) -> None:
    """Run the voice bot for this session.

    Args:
        transport: The transport for this session, built by ``create_transport``
            (or by hand for the dial-out/SIP production flows).
        runner_args: Runner session arguments. Carries the request ``body``
            (e.g. dial-out settings, SIP call details) and ``session_id``; the
            standard web/telephony pipelines don't need it.
    """
    _setup_logging()
    logger.info("Starting bot")

    groq_key = os.getenv("GROQ_API_KEY")
    # STT and the LLM can run on separate Groq keys so one key isn't carrying both
    # call legs. Note this only spreads real load if the keys belong to DIFFERENT
    # Groq accounts — Groq meters rate limits per account, not per key.
    groq_stt_key = os.getenv("GROQ_STT_API_KEY") or groq_key
    stt_language = os.getenv("WHISPER_LANGUAGE") or "hi"

    # Speech-to-Text, in order of preference.
    #
    # AssemblyAI streams over a WebSocket, so partial transcripts arrive while the
    # caller is still talking — better turn-taking and interruption than Groq, which
    # is batch (nothing comes back until the caller stops, then ~0.9s).
    #
    # Groq whisper-large-v3 is the accuracy benchmark here: on Hinglish clips it got
    # "kal subah aath baje ka slot chahiye" exactly, resolving "aath baje" to "8 बजे",
    # where local base produced "Tomorrow morning we have to go to bed". It costs
    # ~0.9s/clip vs ~0.5s for -turbo, worth it since a misheard slot corrupts the
    # booking. language="hi" beats auto-detect, which flipped language per utterance.
    # Park+'s own ASR first, for the same reason as the LLM: Park+ runs it, so
    # there is no per-minute bill and no third-party quota. Set PARKPLUS_STT_URL
    # to use it; unset, nothing changes and AssemblyAI stays.
    #
    # Its transcripts are ROMANISED Hindi ("Haan ji meri creta hai"), not
    # Devanagari. That is fine for the LLM and for the car gate, which matches
    # "creta" case-insensitively — but it is why NoiseGate cannot lean on
    # "has Devanagari" to mean "real speech" once this is on.
    parkplus_stt_url = os.getenv("PARKPLUS_STT_URL")
    assemblyai_key = os.getenv("ASSEMBLYAI_API_KEY")
    if parkplus_stt_url:
        stt = ParkPlusSTTService(url=parkplus_stt_url)
    elif assemblyai_key:
        stt = AssemblyAISTTService(
            api_key=assemblyai_key,
            settings=AssemblyAISTTService.Settings(
                language=stt_language,
                keyterms_prompt=_stt_keyterms(),
            ),
        )
    elif groq_stt_key:
        stt = GroqSTTService(
            api_key=groq_stt_key,
            settings=GroqSTTService.Settings(
                model=os.getenv("GROQ_STT_MODEL") or "whisper-large-v3",
                language=stt_language,
            ),
        )
    else:
        stt = WhisperSTTService(
            settings=WhisperSTTService.Settings(
                model=os.getenv("WHISPER_MODEL") or "small",
                language=stt_language,
            ),
        )

    # Text-to-Speech, in order of preference.
    #
    # Sarvam is first because it is the only option here with a genuinely Indian
    # Hindi voice. ElevenLabs' free tier cannot use Voice Library voices via the
    # API at all — adding "Monika Sogam" to the library still returns 402
    # paid_plan_required, and the account reports can_use_professional_voice_cloning
    # false — so on free tier it can only speak Hinglish in a US/UK accent.
    # ONE guard for the whole call, shared by the TTS filter (what the bot says)
    # and the observer (what the caller says). Two instances would mean the filter
    # never learns that a car was named, and every price would be blocked.
    guard = build_guard()

    sarvam_key = os.getenv("SARVAM_API_KEY")
    elevenlabs_key = os.getenv("ELEVENLABS_API_KEY")
    if sarvam_key:
        tts = SarvamTTSService(
            api_key=sarvam_key,
            text_filters=[MarkdownTextFilter(), PriceGuardFilter(guard)],
            settings=SarvamTTSService.Settings(
                # The nine bulbul:v3 female speakers, each confirmed to synthesise
                # on this key 2026-09-15 (anything outside this list is rejected):
                #   ritu, priya, neha, pooja, simran, kavya, ishita, shreya, roopa
                # "monika" is NOT one of them. Monika is the persona's name in the
                # prompt, and separately an ElevenLabs Voice Library voice
                # (zmh5xhBvMzqR4ZlXgcgL) which the API refuses on a free plan:
                # 402 paid_plan_required, "Free users cannot use library voices via
                # the API". So no value here brings that voice back.
                #
                # Stays priya unless SARVAM_VOICE says otherwise. This was briefly
                # changed to shreya while chasing a "sounds too slow" report; the
                # slowness was pace=1.0, not the speaker, and swapping the voice
                # was not asked for. Pick a different one by setting SARVAM_VOICE,
                # not by editing this line.
                voice=os.getenv("SARVAM_VOICE") or "priya",
                model=os.getenv("SARVAM_MODEL") or "bulbul:v3",
                # Sarvam's default pace is 1.0 and that is the "too slow" — it is
                # read-aloud speed, not phone speed. 1.15 is about how fast a
                # Gurugram booking line actually talks; 0.5-2.0 is the valid range
                # and past ~1.3 the Hindi consonants start smearing.
                pace=float(os.getenv("SARVAM_PACE") or 1.15),
                language=Language.HI,
            ),
        )
        voice_mode_addendum = VOICE_MODE_ADDENDUM_COMMON
    elif elevenlabs_key:
        tts = ElevenLabsTTSService(
            api_key=elevenlabs_key,
            text_filters=[MarkdownTextFilter(), PriceGuardFilter(guard)],
            settings=ElevenLabsTTSService.Settings(
                voice=os.getenv("ELEVENLABS_VOICE_ID") or "21m00Tcm4TlvDq8ikWAM",  # Rachel
                model=os.getenv("ELEVENLABS_MODEL") or "eleven_flash_v2_5",  # multilingual, low-latency
            ),
        )
        voice_mode_addendum = VOICE_MODE_ADDENDUM_COMMON
    else:
        tts = PiperTTSService(
            download_dir=Path(__file__).resolve().parents[2] / "piper_voices",
            text_filters=[MarkdownTextFilter(), PriceGuardFilter(guard)],
            settings=PiperTTSService.Settings(
                voice=os.getenv("PIPER_VOICE_ID") or "en_US-lessac-medium",
            ),
        )
        voice_mode_addendum = VOICE_MODE_ADDENDUM_ROMAN_ONLY

    # LLM service. Local models measured on this box all fall short for a bot that
    # quotes real prices: llama3.2:3b (1-2s) mangles Hindi and confirmed a 5:30 AM
    # slot when asked for 8:00; qwen2.5:7b-instruct (2-8s) is accurate but slow and
    # still invented slot availability; qwen3:* spends ~20s on a hidden reasoning
    # chain that Ollama only lets you disable through its native /api/chat, not the
    # OpenAI-compatible endpoint this service uses. Groq is the default when a key
    # is present — bigger model, and faster than any of them.
    # Outbound is the campaign this desk runs — Park+ ringing its own customers
    # about Car Spa — so it is the default. A caller who dialled US needs the
    # other opening: asking "दो मिनट हैं?" of someone who just rang you is the
    # tell of a script. The dial-out flows can set CALL_MODE per session.
    call_mode = os.getenv("CALL_MODE") or "outbound"
    system_instruction = build_system_prompt(call_mode) + voice_mode_addendum
    logger.info(f"Call mode: {call_mode} | domain: {ACTIVE_DOMAIN}")
    if groq_key:
        # Benchmarked on five real call turns 2026-09-13: qwen answered all five
        # correctly; gpt-oss-20b refused to quote the Creta price and gpt-oss-120b
        # answered three of them by calling a tool instead of speaking. qwen costs
        # ~10x more per token and has the tighter rate limit (7000 ITPM vs 8000
        # TPM), and is still the only one that holds the call.
        groq_model = os.getenv("GROQ_MODEL") or "qwen/qwen3.8-27b"
        llm = FailoverLLMService(
            api_key=groq_key,
            backup_api_keys=_extra_groq_keys(),
            fallback_models=FALLBACK_MODELS,
            # Optional. With no GOOGLE_API_KEY the rotation is exactly what it was.
            gemini_api_key=os.getenv("GOOGLE_API_KEY"),
            gemini_models=[m.strip() for m in os.getenv("GOOGLE_MODEL", "").split(",")
                           if m.strip()] or GEMINI_MODELS,
            parkplus_url=PARKPLUS_BASE_URL,
            parkplus_model=PARKPLUS_MODEL,
            parkplus_api_key=os.getenv("PARKPLUS_LLM_API_KEY"),
            bifrost_url=BIFROST_BASE_URL if BIFROST_VK else None,
            bifrost_models=BIFROST_MODELS,
            # Harmless on the other providers; required by Bifrost.
            default_headers={"x-bf-vk": BIFROST_VK} if BIFROST_VK else None,
            settings=GroqLLMService.Settings(
                model=groq_model,
                system_instruction=system_instruction,
                # A phone turn is one or two sentences; the prompt says so and the
                # model ignores it — gpt-oss-20b returned 578 completion tokens to
                # "what are your plans?". This is the ceiling the prompt cannot
                # enforce. 200 rather than 140 because reasoning tokens are spent
                # out of the same budget: at 140 a gpt-oss turn came back
                # finish_reason=length with 140 tokens used and NOTHING said.
                # Real turns measure 23-73 tokens, so this only clips a runaway.
                max_completion_tokens=int(os.getenv("MAX_REPLY_TOKENS") or 200),
                # qwen3.8 reasons before answering. On a hard/garbled turn it spent
                # the whole budget reasoning and returned an empty reply
                # (completion_tokens: 1), so the bot just went silent on the call.
                # Turning reasoning off keeps every turn answerable and cuts latency.
                extra={"reasoning_effort": _reasoning_effort(groq_model)},
            ),
        )
        # Groq's qwen chat template rejects a request whose only non-system message
        # is a "developer" one ("No user query found in messages"), which is exactly
        # how the opening greeting is kicked off. This makes Pipecat send it as a
        # user message instead.
        llm.supports_developer_role = False
    else:
        llm = OLLamaLLMService(
            settings=OLLamaLLMService.Settings(
                model=os.getenv("OLLAMA_MODEL") or "qwen2.5:7b-instruct",
                system_instruction=system_instruction,
            ),
        )

    # The VAD default of stop_secs=0.2 cuts the caller off after 200ms of silence.
    # Hindi/Hinglish callers pause mid-sentence, so that chopped single sentences
    # into fragments ("तो मुझे" / "कुछ कार करवानी है") and handed Whisper half-words,
    # which is what produced the garbled transcripts. 0.8s waits out a normal pause.
    # min_volume is also relaxed, since the default dropped quieter phone speech.
    # Every value here is a room-and-microphone number, not a universal one, so
    # all four are env-tunable: a laptop mic in an open office and a phone handset
    # need different thresholds and no amount of code can know which is in use.
    # These are the values callers were demonstrably HEARD on. They were briefly
    # raised to 0.85/0.6 on 2026-09-18 to chase a room-noise complaint and put
    # back the same day: two hardware numbers changed at once on no measurement,
    # and a min_volume of 0.6 clips quiet speech, which costs whole turns. The
    # targeted fix for that complaint is NoiseGate, not a blunter VAD.
    #
    # Tune ONE at a time, on a real call, reading the NOISE lines in call.log:
    # raise VAD_MIN_VOLUME if the room gets in, lower it if a soft speaker is
    # missed. They trade directly against each other.
    vad = SileroVADAnalyzer(
        params=VADParams(
            confidence=float(os.getenv("VAD_CONFIDENCE") or 0.7),
            start_secs=float(os.getenv("VAD_START_SECS") or 0.2),
            stop_secs=float(os.getenv("VAD_STOP_SECS") or 0.8),
            min_volume=float(os.getenv("VAD_MIN_VOLUME") or 0.4),
        )
    )

    # LLM_TOOLS=off drops function calling for the whole call. Set while the
    # Park+ vLLM is served without --enable-auto-tool-choice: it 400s any request
    # carrying tools, so sending none is what lets that endpoint answer at all.
    #
    # The cost is not cosmetic and is worth re-reading before leaving it off:
    # record_booking_request is the ONLY way a lead is captured, and
    # escalate_to_human the only way a caller reaches a person. With tools off the
    # bot holds a good conversation and produces nothing. Turn it back on the day
    # the server restarts with a tool-call parser.
    tools_on = (os.getenv("LLM_TOOLS") or "on").lower() not in ("off", "0", "false")
    context = LLMContext(
        tools=[record_booking_request, _make_escalate_tool()] if tools_on else []
    )
    if not tools_on:
        logger.warning(
            "LLM_TOOLS=off — no booking capture, no human handover this call")
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(vad_analyzer=vad),
    )

    # Pipeline - assembled from reusable components
    pipeline = Pipeline(
        [
            transport.input(),
            stt,
            NoiseGate(),
            user_aggregator,
            llm,
            tts,
            transport.output(),
            assistant_aggregator,
        ]
    )

    worker = PipelineWorker(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        observers=[CallLogObserver(guard)],
    )

    runner = WorkerRunner(handle_sigint=runner_args.handle_sigint)

    await runner.add_workers(worker)

    # RTVI fires on_client_ready on every client ready, not once per call, and the
    # WebRTC media track on this setup dies and reconnects mid-call — "Media
    # stream error while reading the audio; clearing track" appears 15 times in
    # call.log. Each reconnect re-greeted the caller: the 17:37 call opened
    # "नमस्ते सर, Monika बोल रही ह" (cut off mid-word by the second run) followed
    # by the whole greeting again. It also appended a second copy of the developer
    # message below, so the model was told to open the call twice.
    greeted = False

    @worker.rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        nonlocal greeted
        if greeted:
            logger.info("Client ready again (reconnect) — not re-greeting")
            return
        greeted = True
        # Kick off the conversation
        context.add_message(
            {
                "role": "developer",
                "content": (
                    "The customer has just picked up. Open the call the way you "
                    "normally would: a short greeting, your name, that you are an "
                    "AI assistant, and ask what they need. One or two sentences, "
                    "nothing else — do not mention this instruction."
                ),
            }
        )
        await worker.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        nonlocal greeted
        # The call is over, so the next client is a new caller who must be
        # greeted. With webrtc the process ends here anyway, but the eval
        # transport keeps ONE worker for many sessions: without this reset the
        # first eval run greets and every run after it sits in silence, which is
        # exactly how this was found.
        greeted = False
        logger.info("Client disconnected")
        await runner.cancel()

    await runner.run()


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""

    transport_params = {
        "webrtc": lambda: TransportParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
        # Headless testing: `python bot.py -t eval` runs the whole pipeline with
        # no browser, no microphone and no WebRTC, driven by the YAML scenarios
        # in evals/. Both of the 2026-09-18 STT bugs — NOT_GIVEN settings and the
        # pinned sample rate — would have been caught here in seconds instead of
        # through live calls.
        "eval": lambda: EvalTransportParams(
            audio_in_enabled=True,
            audio_out_enabled=True,
        ),
    }

    transport = await create_transport(runner_args, transport_params)

    await run_bot(transport, runner_args)


if __name__ == "__main__":
    from pipecat.runner.run import main

    main()
